LIDAR_SCAN_UPDATES = 1
LIDAR_HORIZONTAL_RESOLUTION = 200
LIDAR_FOV = 6.28
ROBOT_TIMESTEP = 100

GRID_RESOLUTION = 0.001
GRID_ORIGIN = [0.0, 0.0]
PERCENT_OF_TOTAL = 0.1 # Percentage of total points percentage to use as threshold for outliers
